plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.videolyricexport'
version = '1.0.0'

android {
  namespace "expo.modules.videolyricexport"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  def media3 = "1.8.0"
  implementation "androidx.media3:media3-transformer:$media3"
  implementation "androidx.media3:media3-effect:$media3"
  implementation "androidx.media3:media3-common:$media3"
}
